services:
  web:
  environment:
      - PYTHONPATH=/app
  build: .
  ports:
      - "5421:5421"
  env_file:
      - .env
  epends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"